vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /images/users/avatars
            upload_destination: '%kernel.project_dir%/public/images/users/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        banners:
            uri_prefix: /images/users/banners
            upload_destination: '%kernel.project_dir%/public/images/users/banners'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
