<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'AverageColor' => [
        'path' => './assets/js/images/AverageColor.js',
    ],
    'HighlightSeries' => [
        'path' => './assets/js/home/HighlightSeries.js',
    ],
    'Menu' => [
        'path' => './assets/js/Menu.js',
    ],
    'NavBar' => [
        'path' => './assets/js/NavBar.js',
    ],
    'PosterHover' => [
        'path' => './assets/js/images/PosterHover.js',
    ],
    'ProviderSelect' => [
        'path' => './assets/js/home/ProviderSelect.js',
    ],
    'ToolTips' => [
        'path' => './assets/js/ToolTips.js',
    ],
    'Season' => [
        'path' => './assets/js/series/Season.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/turbo' => [
        'version' => '7.3.0',
    ],
];
